<?php
namespace Tests\Feature;
use App\Models\Category; use App\Models\Product; use App\Models\Store; use App\Models\User; use App\Models\CartItem; use App\Services\CartCalculationService; use Illuminate\Foundation\Testing\RefreshDatabase; use Tests\TestCase;
class CartCheckoutTotalsAuditTest extends TestCase {
 use RefreshDatabase;
 private function storeWithProd(float $price, ?float $sale=null, array $variant=null): array {
  $plan=\App\Models\Plan::factory()->create(['max_products_per_store'=>1000,'max_stores'=>10,'themes'=>['all']]);
  $user=User::factory()->create(['type'=>'company','email_verified_at'=>now(),'onboarded_at'=>now(),'plan_id'=>$plan->id,'plan_expire_date'=>now()->addMonth()]);
  $store=Store::factory()->create(['user_id'=>$user->id]); $user->current_store=$store->id; $user->save();
  $cat=Category::factory()->create(['store_id'=>$store->id,'is_active'=>true]);
  $data=['name'=>'P','price'=>$price,'stock'=>10,'store_id'=>$store->id,'category_id'=>$cat->id,'images'=>'/storage/a.jpg','cover_image'=>'/storage/a.jpg','is_active'=>true];
  if($sale!==null) $data['sale_price']=$sale;
  if($variant){ $data['variants']=json_encode([['name'=>'Size','values'=>['S','XL']]]); $data['variant_combinations']=json_encode([['id'=>'S','values'=>['S'],'label'=>'S','price'=>(string)$price],['id'=>'XL','values'=>['XL'],'label'=>'XL','price'=>(string)$variant['price']]]); }
  $p=Product::create($data);
  return [$store,$p];
 }
 public function test_base_total(): void { [$store,$p]=$this->storeWithProd(100); CartItem::create(['store_id'=>$store->id,'session_id'=>'s1','product_id'=>$p->id,'quantity'=>2,'price'=>$p->effectivePrice()]); $c=CartCalculationService::calculateCartTotals($store->id,'s1'); $this->assertEquals(200,$c['subtotal']); $this->assertEquals(200,$c['total']); }
 public function test_sale_total(): void { [$store,$p]=$this->storeWithProd(100,80); CartItem::create(['store_id'=>$store->id,'session_id'=>'s2','product_id'=>$p->id,'quantity'=>1,'price'=>$p->effectivePrice()]); $c=CartCalculationService::calculateCartTotals($store->id,'s2'); $this->assertEquals(80,$c['subtotal']); }
 public function test_variant_total(): void { [$store,$p]=$this->storeWithProd(100,null,['price'=>130]); CartItem::create(['store_id'=>$store->id,'session_id'=>'s3','product_id'=>$p->id,'quantity'=>2,'variants'=>json_encode(['Size'=>'XL']),'price'=>130]); $c=CartCalculationService::calculateCartTotals($store->id,'s3'); $this->assertEquals(260,$c['subtotal']); }
 public function test_coupon_percentage(): void { [$store,$p]=$this->storeWithProd(100); \App\Models\StoreCoupon::create(['store_id'=>$store->id,'name'=>'Test','code'=>'TEST10','type'=>'percentage','discount_amount'=>10,'status'=>true,'minimum_spend'=>0]); CartItem::create(['store_id'=>$store->id,'session_id'=>'s4','product_id'=>$p->id,'quantity'=>2,'price'=>100]); $c=CartCalculationService::calculateCartTotals($store->id,'s4','TEST10'); $this->assertEquals(200,$c['subtotal']); $this->assertEquals(20,$c['discount']); $this->assertEquals(180,$c['total']); }
 public function test_tax_exclusive(): void { [$store,$p]=$this->storeWithProd(100); $p->is_tax_included=false; $p->save(); $tax=\App\Models\Tax::create(['store_id'=>$store->id,'name'=>'VAT','rate'=>10,'type'=>'percentage','is_active'=>true]); $p->tax_id=$tax->id; $p->save(); CartItem::create(['store_id'=>$store->id,'session_id'=>'s5','product_id'=>$p->id,'quantity'=>2,'price'=>100]); $c=CartCalculationService::calculateCartTotals($store->id,'s5'); $this->assertEquals(200,$c['subtotal']); $this->assertEquals(20,$c['tax']); $this->assertEquals(220,$c['total']); }
 public function test_tax_inclusive(): void { [$store,$p]=$this->storeWithProd(100); $p->is_tax_included=true; $p->save(); \App\Models\Setting::setSetting('prices_include_tax','1',$store->user_id,$store->id); $tax=\App\Models\Tax::create(['store_id'=>$store->id,'name'=>'VAT','rate'=>10,'type'=>'percentage','is_active'=>true]); $p->tax_id=$tax->id; $p->save(); CartItem::create(['store_id'=>$store->id,'session_id'=>'sIncl','product_id'=>$p->id,'quantity'=>1,'price'=>100]); $c=CartCalculationService::calculateCartTotals($store->id,'sIncl'); $this->assertEquals(100,$c['subtotal']); $this->assertEqualsWithDelta(9.09,$c['tax'],0.01); $this->assertEquals(100,$c['total']); }
 public function test_backend_ignores_frontend_price_tampering(): void { [$store,$p]=$this->storeWithProd(100); CartItem::create(['store_id'=>$store->id,'session_id'=>'s6','product_id'=>$p->id,'quantity'=>1,'price'=>1]); $c=CartCalculationService::calculateCartTotals($store->id,'s6'); $this->assertEquals(100,$c['subtotal']); }
 public function test_shipping_isolated(): void { [$store,$p]=$this->storeWithProd(100); $ship=\App\Models\Shipping::create(['store_id'=>$store->id,'name'=>'Ship','cost'=>15,'type'=>'fixed','is_active'=>true]); CartItem::create(['store_id'=>$store->id,'session_id'=>'s7','product_id'=>$p->id,'quantity'=>1,'price'=>100]); $c=CartCalculationService::calculateCartTotals($store->id,'s7',null,$ship->id); $this->assertEquals(15,$c['shipping']); // fake shipping from other store rejected
  [$store2,$p2]=$this->storeWithProd(100); $ship2=\App\Models\Shipping::create(['store_id'=>$store2->id,'name'=>'Other','cost'=>999,'type'=>'fixed','is_active'=>true]); $c2=CartCalculationService::calculateCartTotals($store->id,'s7',null,$ship2->id); $this->assertEquals(0,$c2['shipping']); }
}
