export interface Country {
    code: string;
    /** Arabic display name */
    name: string;
    /** English name, used for search */
    nameEn: string;
    dialCode: string;
    flag: string;
}

// [ISO 3166-1 alpha-2, Arabic name, English name, dial code]
type RawCountry = [string, string, string, string];

const RAW_COUNTRIES: RawCountry[] = [
    // Frequently requested first
    ['PS', 'فلسطين', 'Palestine', '+970'],
    ['IL', 'إسرائيل', 'Israel', '+972'],
    ['US', 'الولايات المتحدة', 'United States', '+1'],
    ['TR', 'تركيا', 'Turkey', '+90'],
    ['DE', 'ألمانيا', 'Germany', '+49'],
    ['FR', 'فرنسا', 'France', '+33'],
    ['PT', 'البرتغال', 'Portugal', '+351'],
    ['CN', 'الصين', 'China', '+86'],
    ['AR', 'الأرجنتين', 'Argentina', '+54'],
    ['BR', 'البرازيل', 'Brazil', '+55'],
    // Arab world
    ['SA', 'السعودية', 'Saudi Arabia', '+966'],
    ['AE', 'الإمارات', 'United Arab Emirates', '+971'],
    ['JO', 'الأردن', 'Jordan', '+962'],
    ['EG', 'مصر', 'Egypt', '+20'],
    ['IQ', 'العراق', 'Iraq', '+964'],
    ['SY', 'سوريا', 'Syria', '+963'],
    ['LB', 'لبنان', 'Lebanon', '+961'],
    ['KW', 'الكويت', 'Kuwait', '+965'],
    ['QA', 'قطر', 'Qatar', '+974'],
    ['BH', 'البحرين', 'Bahrain', '+973'],
    ['OM', 'عمان', 'Oman', '+968'],
    ['YE', 'اليمن', 'Yemen', '+967'],
    ['DZ', 'الجزائر', 'Algeria', '+213'],
    ['MA', 'المغرب', 'Morocco', '+212'],
    ['TN', 'تونس', 'Tunisia', '+216'],
    ['LY', 'ليبيا', 'Libya', '+218'],
    ['SD', 'السودان', 'Sudan', '+249'],
    ['SO', 'الصومال', 'Somalia', '+252'],
    ['MR', 'موريتانيا', 'Mauritania', '+222'],
    ['DJ', 'جيبوتي', 'Djibouti', '+253'],
    ['KM', 'جزر القمر', 'Comoros', '+269'],
    // Rest of the world
    ['AF', 'أفغانستان', 'Afghanistan', '+93'],
    ['AL', 'ألبانيا', 'Albania', '+355'],
    ['AD', 'أندورا', 'Andorra', '+376'],
    ['AO', 'أنغولا', 'Angola', '+244'],
    ['AI', 'أنغويلا', 'Anguilla', '+1264'],
    ['AG', 'أنتيغوا وبربودا', 'Antigua and Barbuda', '+1268'],
    ['AM', 'أرمينيا', 'Armenia', '+374'],
    ['AW', 'أروبا', 'Aruba', '+297'],
    ['AU', 'أستراليا', 'Australia', '+61'],
    ['AT', 'النمسا', 'Austria', '+43'],
    ['AZ', 'أذربيجان', 'Azerbaijan', '+994'],
    ['BS', 'الباهاما', 'Bahamas', '+1242'],
    ['BD', 'بنغلاديش', 'Bangladesh', '+880'],
    ['BB', 'بربادوس', 'Barbados', '+1246'],
    ['BY', 'بيلاروس', 'Belarus', '+375'],
    ['BE', 'بلجيكا', 'Belgium', '+32'],
    ['BZ', 'بليز', 'Belize', '+501'],
    ['BJ', 'بنين', 'Benin', '+229'],
    ['BM', 'برمودا', 'Bermuda', '+1441'],
    ['BT', 'بوتان', 'Bhutan', '+975'],
    ['BO', 'بوليفيا', 'Bolivia', '+591'],
    ['BA', 'البوسنة والهرسك', 'Bosnia and Herzegovina', '+387'],
    ['BW', 'بوتسوانا', 'Botswana', '+267'],
    ['IO', 'إقليم المحيط الهندي البريطاني', 'British Indian Ocean Territory', '+246'],
    ['BN', 'بروناي', 'Brunei', '+673'],
    ['BG', 'بلغاريا', 'Bulgaria', '+359'],
    ['BF', 'بوركينا فاسو', 'Burkina Faso', '+226'],
    ['BI', 'بوروندي', 'Burundi', '+257'],
    ['KH', 'كمبوديا', 'Cambodia', '+855'],
    ['CM', 'الكاميرون', 'Cameroon', '+237'],
    ['CA', 'كندا', 'Canada', '+1'],
    ['CV', 'الرأس الأخضر', 'Cape Verde', '+238'],
    ['KY', 'جزر كايمان', 'Cayman Islands', '+1345'],
    ['CF', 'جمهورية أفريقيا الوسطى', 'Central African Republic', '+236'],
    ['TD', 'تشاد', 'Chad', '+235'],
    ['CL', 'تشيلي', 'Chile', '+56'],
    ['CO', 'كولومبيا', 'Colombia', '+57'],
    ['CG', 'الكونغو', 'Congo', '+242'],
    ['CD', 'الكونغو الديمقراطية', 'DR Congo', '+243'],
    ['CK', 'جزر كوك', 'Cook Islands', '+682'],
    ['CR', 'كوستاريكا', 'Costa Rica', '+506'],
    ['CI', 'كوت ديفوار', 'Ivory Coast', '+225'],
    ['HR', 'كرواتيا', 'Croatia', '+385'],
    ['CU', 'كوبا', 'Cuba', '+53'],
    ['CY', 'قبرص', 'Cyprus', '+357'],
    ['CW', 'كوراساو', 'Curacao', '+599'],
    ['CZ', 'التشيك', 'Czechia', '+420'],
    ['DK', 'الدنمارك', 'Denmark', '+45'],
    ['DM', 'دومينيكا', 'Dominica', '+1767'],
    ['DO', 'جمهورية الدومينيكان', 'Dominican Republic', '+1809'],
    ['EC', 'الإكوادور', 'Ecuador', '+593'],
    ['SV', 'السلفادور', 'El Salvador', '+503'],
    ['GQ', 'غينيا الاستوائية', 'Equatorial Guinea', '+240'],
    ['ER', 'إريتريا', 'Eritrea', '+291'],
    ['EE', 'إستونيا', 'Estonia', '+372'],
    ['ET', 'إثيوبيا', 'Ethiopia', '+251'],
    ['FK', 'جزر فوكلاند', 'Falkland Islands', '+500'],
    ['FO', 'جزر فارو', 'Faroe Islands', '+298'],
    ['FJ', 'فيجي', 'Fiji', '+679'],
    ['FI', 'فنلندا', 'Finland', '+358'],
    ['GF', 'غويانا الفرنسية', 'French Guiana', '+594'],
    ['PF', 'بولينيزيا الفرنسية', 'French Polynesia', '+689'],
    ['GA', 'الغابون', 'Gabon', '+241'],
    ['GM', 'غامبيا', 'Gambia', '+220'],
    ['GE', 'جورجيا', 'Georgia', '+995'],
    ['GH', 'غانا', 'Ghana', '+350'],
    ['GI', 'جبل طارق', 'Gibraltar', '+350'],
    ['GR', 'اليونان', 'Greece', '+30'],
    ['GL', 'غرينلاند', 'Greenland', '+299'],
    ['GD', 'غرينادا', 'Grenada', '+1473'],
    ['GP', 'غوادلوب', 'Guadeloupe', '+590'],
    ['GU', 'غوام', 'Guam', '+1671'],
    ['GT', 'غواتيمالا', 'Guatemala', '+502'],
    ['GG', 'غيرنزي', 'Guernsey', '+44'],
    ['GN', 'غينيا', 'Guinea', '+224'],
    ['GW', 'غينيا بيساو', 'Guinea-Bissau', '+245'],
    ['GY', 'غيانا', 'Guyana', '+592'],
    ['HT', 'هايتي', 'Haiti', '+509'],
    ['VA', 'الفاتيكان', 'Vatican City', '+39'],
    ['HN', 'هندوراس', 'Honduras', '+504'],
    ['HK', 'هونغ كونغ', 'Hong Kong', '+852'],
    ['HU', 'المجر', 'Hungary', '+36'],
    ['IS', 'آيسلندا', 'Iceland', '+354'],
    ['IN', 'الهند', 'India', '+91'],
    ['ID', 'إندونيسيا', 'Indonesia', '+62'],
    ['IR', 'إيران', 'Iran', '+98'],
    ['IE', 'أيرلندا', 'Ireland', '+353'],
    ['IM', 'جزيرة مان', 'Isle of Man', '+44'],
    ['IT', 'إيطاليا', 'Italy', '+39'],
    ['JM', 'جامايكا', 'Jamaica', '+1876'],
    ['JP', 'اليابان', 'Japan', '+81'],
    ['JE', 'جيرسي', 'Jersey', '+44'],
    ['KZ', 'كازاخستان', 'Kazakhstan', '+7'],
    ['KE', 'كينيا', 'Kenya', '+254'],
    ['KI', 'كيريباتي', 'Kiribati', '+686'],
    ['KG', 'قرغيزستان', 'Kyrgyzstan', '+996'],
    ['LA', 'لاوس', 'Laos', '+856'],
    ['LV', 'لاتفيا', 'Latvia', '+371'],
    ['LS', 'ليسوتو', 'Lesotho', '+266'],
    ['LR', 'ليبيريا', 'Liberia', '+231'],
    ['LI', 'ليختنشتاين', 'Liechtenstein', '+423'],
    ['LT', 'ليتوانيا', 'Lithuania', '+370'],
    ['LU', 'لوكسمبورغ', 'Luxembourg', '+352'],
    ['MO', 'ماكاو', 'Macau', '+853'],
    ['MG', 'مدغشقر', 'Madagascar', '+261'],
    ['MW', 'ملاوي', 'Malawi', '+265'],
    ['MY', 'ماليزيا', 'Malaysia', '+60'],
    ['MV', 'المالديف', 'Maldives', '+960'],
    ['ML', 'مالي', 'Mali', '+223'],
    ['MT', 'مالطة', 'Malta', '+356'],
    ['MH', 'جزر مارشال', 'Marshall Islands', '+692'],
    ['MQ', 'مارتينيك', 'Martinique', '+596'],
    ['MX', 'المكسيك', 'Mexico', '+52'],
    ['FM', 'ميكرونيزيا', 'Micronesia', '+691'],
    ['MD', 'مولدوفا', 'Moldova', '+373'],
    ['MC', 'موناكو', 'Monaco', '+377'],
    ['MN', 'منغوليا', 'Mongolia', '+976'],
    ['ME', 'الجبل الأسود', 'Montenegro', '+382'],
    ['MS', 'مونتسيرات', 'Montserrat', '+1664'],
    ['MZ', 'موزمبيق', 'Mozambique', '+258'],
    ['MM', 'ميانمار', 'Myanmar', '+95'],
    ['NA', 'ناميبيا', 'Namibia', '+264'],
    ['NR', 'ناورو', 'Nauru', '+674'],
    ['NP', 'نيبال', 'Nepal', '+977'],
    ['NL', 'هولندا', 'Netherlands', '+31'],
    ['NC', 'كاليدونيا الجديدة', 'New Caledonia', '+687'],
    ['NZ', 'نيوزيلندا', 'New Zealand', '+64'],
    ['NI', 'نيكاراغوا', 'Nicaragua', '+505'],
    ['NE', 'النيجر', 'Niger', '+227'],
    ['NG', 'نيجيريا', 'Nigeria', '+234'],
    ['NU', 'نيوي', 'Niue', '+683'],
    ['NF', 'جزيرة نورفولك', 'Norfolk Island', '+672'],
    ['MK', 'شمال مقدونيا', 'North Macedonia', '+389'],
    ['MP', 'جزر ماريانا الشمالية', 'Northern Mariana Islands', '+1670'],
    ['NO', 'النرويج', 'Norway', '+47'],
    ['PK', 'باكستان', 'Pakistan', '+92'],
    ['PW', 'بالاو', 'Palau', '+680'],
    ['PA', 'بنما', 'Panama', '+507'],
    ['PG', 'بابوا غينيا الجديدة', 'Papua New Guinea', '+675'],
    ['PY', 'باراغواي', 'Paraguay', '+595'],
    ['PE', 'بيرو', 'Peru', '+51'],
    ['PH', 'الفلبين', 'Philippines', '+63'],
    ['PL', 'بولندا', 'Poland', '+48'],
    ['PR', 'بورتوريكو', 'Puerto Rico', '+1787'],
    ['RE', 'ريونيون', 'Reunion', '+262'],
    ['RO', 'رومانيا', 'Romania', '+40'],
    ['RU', 'روسيا', 'Russia', '+7'],
    ['RW', 'رواندا', 'Rwanda', '+250'],
    ['KN', 'سانت كيتس ونيفيس', 'Saint Kitts and Nevis', '+1869'],
    ['LC', 'سانت لوسيا', 'Saint Lucia', '+1758'],
    ['VC', 'سانت فينسنت والغرينادين', 'Saint Vincent and the Grenadines', '+1784'],
    ['WS', 'ساموا', 'Samoa', '+685'],
    ['SM', 'سان مارينو', 'San Marino', '+378'],
    ['ST', 'ساو تومي وبرينسيبي', 'Sao Tome and Principe', '+239'],
    ['SN', 'السنغال', 'Senegal', '+221'],
    ['RS', 'صربيا', 'Serbia', '+381'],
    ['SC', 'سيشل', 'Seychelles', '+248'],
    ['SL', 'سيراليون', 'Sierra Leone', '+232'],
    ['SG', 'سنغافورة', 'Singapore', '+65'],
    ['SX', 'سانت مارتن', 'Sint Maarten', '+1721'],
    ['SK', 'سلوفاكيا', 'Slovakia', '+421'],
    ['SI', 'سلوفينيا', 'Slovenia', '+386'],
    ['SB', 'جزر سليمان', 'Solomon Islands', '+677'],
    ['ZA', 'جنوب أفريقيا', 'South Africa', '+27'],
    ['KR', 'كوريا الجنوبية', 'South Korea', '+82'],
    ['SS', 'جنوب السودان', 'South Sudan', '+211'],
    ['ES', 'إسبانيا', 'Spain', '+34'],
    ['LK', 'سريلانكا', 'Sri Lanka', '+94'],
    ['SR', 'سورينام', 'Suriname', '+597'],
    ['SE', 'السويد', 'Sweden', '+46'],
    ['CH', 'سويسرا', 'Switzerland', '+41'],
    ['TW', 'تايوان', 'Taiwan', '+886'],
    ['TJ', 'طاجيكستان', 'Tajikistan', '+992'],
    ['TZ', 'تنزانيا', 'Tanzania', '+255'],
    ['TH', 'تايلاند', 'Thailand', '+66'],
    ['TL', 'تيمور الشرقية', 'Timor-Leste', '+670'],
    ['TG', 'توغو', 'Togo', '+228'],
    ['TK', 'توكيلاو', 'Tokelau', '+690'],
    ['TO', 'تونغا', 'Tonga', '+676'],
    ['TT', 'ترينيداد وتوباغو', 'Trinidad and Tobago', '+1868'],
    ['TM', 'تركمانستان', 'Turkmenistan', '+993'],
    ['TC', 'جزر تركس وكايكوس', 'Turks and Caicos Islands', '+1649'],
    ['TV', 'توفالو', 'Tuvalu', '+688'],
    ['UG', 'أوغندا', 'Uganda', '+256'],
    ['UA', 'أوكرانيا', 'Ukraine', '+380'],
    ['GB', 'المملكة المتحدة', 'United Kingdom', '+44'],
    ['UY', 'أوروغواي', 'Uruguay', '+598'],
    ['UZ', 'أوزبكستان', 'Uzbekistan', '+998'],
    ['VU', 'فانواتو', 'Vanuatu', '+678'],
    ['VE', 'فنزويلا', 'Venezuela', '+58'],
    ['VN', 'فيتنام', 'Vietnam', '+84'],
    ['VG', 'جزر العذراء البريطانية', 'British Virgin Islands', '+1284'],
    ['VI', 'جزر العذراء الأمريكية', 'U.S. Virgin Islands', '+1340'],
    ['WF', 'واليس وفوتونا', 'Wallis and Futuna', '+681'],
    ['ZM', 'زامبيا', 'Zambia', '+260'],
    ['ZW', 'زيمبابوي', 'Zimbabwe', '+263'],
];

/** Emoji flag computed from the ISO alpha-2 code (regional indicator symbols). */
const flagFromCode = (code: string): string =>
    code.replace(/./g, (ch) => String.fromCodePoint(127397 + ch.charCodeAt(0)));

export const COUNTRIES: Country[] = RAW_COUNTRIES.map(([code, name, nameEn, dialCode]) => ({
    code,
    name,
    nameEn,
    dialCode,
    flag: flagFromCode(code),
}));
